# Generated by Django 3.2.7 on 2021-09-23 12:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'CVmaker',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_format', models.CharField(choices=[('traditional', 'traditional'), ('banking', 'banking'), ('normal', 'normal'), ('modern', 'modern'), ('fancy', 'fancy'), ('superficial', 'superficial')], help_text='Choose CV format in drop down list.', max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateTimeField(default='yyyy-mm-dd', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Home_address', models.CharField(blank=True, max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('BSc', models.CharField(blank=True, help_text='BSc title, University name.', max_length=200)),
                ('BSc_start_date', models.DateTimeField(blank=True, null=True)),
                ('BSc_end_date', models.DateTimeField(blank=True, null=True)),
                ('MSc', models.CharField(blank=True, help_text="Skip if you don't have one.", max_length=200)),
                ('MSc_start_date', models.DateTimeField(blank=True, null=True)),
                ('MSc_end_date', models.DateTimeField(blank=True, null=True)),
                ('training', models.CharField(blank=True, help_text="Skip if you don't have one.", max_length=200)),
                ('training_start_date', models.DateTimeField(blank=True, null=True)),
                ('training_end_date', models.DateTimeField(blank=True, null=True)),
                ('work_experience', models.CharField(blank=True, help_text="Skip if you don't have one.", max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('work_exp_start_date', models.DateTimeField(blank=True, null=True)),
                ('work_exp_end_date', models.DateTimeField(blank=True, null=True)),
                ('computer_skills', models.CharField(blank=True, help_text='List all skills from higher to lower.', max_length=500)),
                ('other_skills', models.CharField(blank=True, help_text='Your personal qualities other than proffesional skills?', max_length=1000)),
                ('references', models.CharField(blank=True, help_text='Name email address and phone.', max_length=2000)),
                ('photo', models.FileField(blank=True, help_text='Recomended but not mandatory.', upload_to='')),
                ('cvmaker', models.ManyToManyField(help_text='By selecting RATIFY I hereby declare that the information provided is true and correct.', to='cv.CVmaker')),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
    ]
